#include <stdint.h>
#include "annepro2.h"
#include "qmk_ap2_led.h"
#include "config.h"

enum anne_pro_layers {
  _BASE_LAYER,
  _FN1_TOGGLE_LAYER,
  _SHIFT_LAYER,
  _NUM1_LAYER,
  _NUM2_LAYER,
  _MOVE_LAYER,
  _FN1_PRESS_LAYER,
  _FN2_LAYER,
};

 const uint16_t keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
 [_BASE_LAYER] = KEYMAP( /* Base */
    KC_GESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_UNDS, KC_EQL, KC_BSPC,
    KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_DEL,
    LCTL_T(KC_CAPS), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, MO(_FN2_LAYER), KC_QUOT, KC_ENT,
    MO(_SHIFT_LAYER), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_UP,
    MO(_FN1_PRESS_LAYER), KC_LGUI, KC_LALT, KC_SPC, KC_RALT, KC_LEFT, KC_DOWN, KC_RGHT
),
 [_FN1_TOGGLE_LAYER] = KEYMAP( /* Base */
    KC_TRNS, TO(_BASE_LAYER), TO(_FN1_TOGGLE_LAYER), TO(_NUM1_LAYER), TO(_NUM2_LAYER), TO(_MOVE_LAYER), KC_F6, KC_F7, KC_F8, S(KC_9), S(KC_0), KC_F11, KC_F12, KC_TRNS,
    KC_DEL, KC_HOME, KC_UP, KC_END, C(KC_LEFT), C(KC_Z), C(KC_C), KC_HOME, KC_UP, KC_END, KC_BSPC, KC_TRNS, KC_INS, KC_TRNS,
    KC_TRNS, KC_LEFT, KC_DOWN, KC_RGHT, C(KC_RGHT), KC_TRNS, C(KC_RGHT), KC_LEFT, KC_DOWN, KC_RGHT, KC_SCLN, KC_TRNS, KC_TRNS,
    KC_LSFT, KC_PGUP, KC_PGDN, KC_BSPC, C(KC_V), KC_TRNS, KC_TRNS, KC_PGUP, KC_PGDN, KC_TRNS, KC_TRNS, KC_RSFT,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
),
 [_SHIFT_LAYER] = KEYMAP( /* Base */
    S(KC_ESC), S(KC_1), S(KC_2), S(KC_3), S(KC_4), S(KC_5), S(KC_6), S(KC_7), S(KC_8), S(KC_9), S(KC_0), KC_MINS, S(KC_EQL), S(KC_BSPC),
    S(KC_TAB), S(KC_Q), S(KC_W), S(KC_E), S(KC_R), S(KC_T), S(KC_Y), S(KC_U), S(KC_I), S(KC_O), S(KC_P), S(KC_LBRC), S(KC_RBRC), S(KC_BSLS),
    KC_TRNS, S(KC_A), S(KC_S), S(KC_D), S(KC_F), S(KC_G), S(KC_H), S(KC_J), S(KC_K), S(KC_L), S(KC_SCLN), S(KC_QUOT), S(KC_ENT),
    KC_TRNS, S(KC_Z), S(KC_X), S(KC_C), S(KC_V), S(KC_B), S(KC_N), S(KC_M), S(KC_COMM), S(KC_DOT), S(KC_SLSH), S(KC_UP),
    KC_TRNS, KC_TRNS, KC_TRNS, TO(_FN1_TOGGLE_LAYER), KC_TRNS, S(KC_LEFT), S(KC_DOWN), S(KC_RGHT)
 ),
 [_NUM1_LAYER] = KEYMAP( /* Base */
    KC_TRNS, TO(_BASE_LAYER), TO(_FN1_TOGGLE_LAYER), TO(_NUM1_LAYER), TO(_NUM2_LAYER), TO(_MOVE_LAYER), KC_TRNS, KC_TRNS, S(KC_8), S(KC_9), S(KC_0), KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_0, KC_0, KC_0, KC_0, KC_TRNS, KC_TRNS, KC_0, KC_0, KC_0, KC_0, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_TRNS, KC_TRNS,
    KC_LSFT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_UP,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_RGHT
 ),
 [_NUM2_LAYER] = KEYMAP( /* Base */
    KC_TRNS, TO(_BASE_LAYER), TO(_FN1_TOGGLE_LAYER), TO(_NUM1_LAYER), TO(_NUM2_LAYER), TO(_MOVE_LAYER), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_7, KC_8, KC_9, KC_TRNS, KC_TRNS, C(KC_LEFT), KC_HOME, KC_UP, KC_END, KC_BSPC, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_4, KC_5, KC_6, KC_TRNS, KC_TRNS, C(KC_RGHT), KC_LEFT, KC_DOWN, KC_RGHT, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_0, KC_1, KC_2, KC_3, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_UP,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_RGHT
 ),
  [_MOVE_LAYER] = KEYMAP( /* Base */
    TO(_BASE_LAYER), TO(_BASE_LAYER), TO(_FN1_TOGGLE_LAYER), TO(_NUM1_LAYER), TO(_NUM2_LAYER), TO(_MOVE_LAYER), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_AP_LED_OFF, KC_AP_LED_ON,
    KC_TRNS, KC_AP2_BT1, KC_AP2_BT2, KC_AP2_BT3, KC_AP2_BT4, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_AP_LED_SPEED, KC_AP_LED_NEXT_INTENSITY, KC_AP_LED_PREV_PROFILE, KC_AP_LED_NEXT_PROFILE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_LSFT, KC_VOLD, KC_VOLU, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BRIU,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_MPLY, KC_TRNS, KC_VOLD, KC_BRID, KC_VOLU
 ),
 [_FN1_PRESS_LAYER] = KEYMAP( /* Base */
    KC_GRV, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_TRNS,
    KC_DEL, KC_HOME, KC_UP, KC_END, C(KC_LEFT), C(KC_Z), C(KC_C), KC_HOME, KC_UP, KC_END, KC_BSPC, KC_TRNS, KC_INS, KC_BSLS,
    KC_TRNS, KC_LEFT, KC_DOWN, KC_RGHT, C(KC_RGHT), KC_TRNS, C(KC_RGHT), KC_LEFT, KC_DOWN, KC_RGHT, KC_SCLN, KC_TRNS, KC_TRNS,
    KC_LSFT, KC_PGUP, KC_PGDN, KC_BSPC, C(KC_V), KC_TRNS, KC_TRNS, KC_PGUP, KC_PGDN, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, TO(_NUM1_LAYER), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
 ),
 [_FN2_LAYER] = KEYMAP( /* Base */
    KC_GRV, KC_LPRN, KC_RPRN, KC_LBRC, KC_RBRC, KC_ASTR, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_DEL, KC_HOME, KC_UP, KC_END, C(KC_LEFT), KC_VOLU, C(KC_LEFT), KC_HOME, KC_UP, KC_END, KC_TRNS, KC_BRIU, KC_VOLD, KC_VOLU,
    KC_TRNS, KC_LEFT, KC_DOWN, KC_RGHT, C(KC_RGHT), KC_VOLD, C(KC_RGHT), KC_LEFT, KC_DOWN, KC_RGHT, KC_TRNS, KC_BRID, S(KC_ENT),
    KC_LSFT, KC_TRNS, KC_TRNS, KC_BSPC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_HOME, KC_TRNS, KC_END
 ),
};
const uint16_t keymaps_size = sizeof(keymaps);


void matrix_init_user(void) {

}

void matrix_scan_user(void) {
}

// Code to run after initializing the keyboard
void keyboard_post_init_user(void) {
    // Here are two common functions that you can use. For more LED functions, refer to the file "qmk_ap2_led.h"

    // annepro2-shine disables LEDs by default. Uncomment this function to enable them at startup.
    // annepro2LedEnable();

    // Additionally, it also chooses the first LED profile by default. Refer to the "profiles" array in main.c in
    // annepro2-shine to see the order. Replace "i" with the index of your preferred profile. (i.e the RED profile is index 0)
    // annepro2LedSetProfile(i);
}

layer_state_t layer_state_set_user(layer_state_t layer) {
    return layer;
}